### ISSUE TITLE
how can i run backdoor ?

### ISSUE THREAD

**Issue by evilginx** [blacknbunny/mcreator#2]
hello.. i compiled backdoor . but it is not exe ? how i will run backdoor ?

**Comment by blacknbunny** [comment]
Hello you can compile and run with this commands :

cd lib/

gcc lib/decode.c lib/pwshell.c -o pwshell.exe

Listen the ip & port with netcat or something like that and run backdoor on remote system.

Here is an example to tool how can you use it : https://github.com/blacknbunny/mcreator/wiki/An-example

**Comment by diewithurlie** [comment]
can't run the .exe file

**Comment by exp-db** [comment]
can not run the pwshell.exe, this is detail:
[Window Title]
C:\Users\xxxx\Desktop\pwshell.exe

[Content]
The version of this file is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need an x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.

[OK]

**Comment by blacknbunny** [comment]
"The version of this file is not compatible with the version of Windows you're running." : 
https://goo.gl/A6jpi9
