### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by ghost** [blacknbunny/mcreator#5]
I have read your code.Your way to bypass av is using the garbage strings.So,if I modify the strings,will it be the new ways to bypass?
 
Maybe when I find a new way,i will talk about it.

**Comment by ghost** [comment]
In my realize,this payload looks like 

>
(garbage strings,garbage strings,garbage strings,garbage strings,garbage strings,garbage strings,garbage strings,garbage strings......*so many), TRUE PAYLOAD
>
And AV will give up check it,because it is too long.
So,if I make the strings longer and add some confused strings,and will it be undetectable again?

**Comment by blacknbunny** [comment]
Hello, pple7000.

Toomuchmem and increment techniques bypassing AV's cuz of the garbage memory for the AV software's.

It will giving so much memory to the AV. So av can't see the main dangerous functions, codes.

It's not about confused strings its about how much you fill the AV memory.

Have a nice day

**Comment by ghost** [comment]
Thank you,I realized.
